language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1

addons:
  hosts:
    - blank

sudo: false

install:
  - composer install

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
